# Generated by Django 3.2.8 on 2021-10-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='account',
            field=models.CharField(max_length=60, null=True, verbose_name='账户号'),
        ),
        migrations.AlterField(
            model_name='information',
            name='backstage_staff',
            field=models.CharField(max_length=60, null=True, verbose_name='认领后台员'),
        ),
        migrations.AlterField(
            model_name='information',
            name='belong',
            field=models.CharField(max_length=60, null=True, verbose_name='券商'),
        ),
        migrations.AlterField(
            model_name='information',
            name='business_department',
            field=models.CharField(max_length=120, null=True, verbose_name='所属营业部'),
        ),
        migrations.AlterField(
            model_name='information',
            name='card_sh',
            field=models.CharField(max_length=60, null=True, verbose_name='上海卡号'),
        ),
        migrations.AlterField(
            model_name='information',
            name='card_sz',
            field=models.CharField(max_length=60, null=True, verbose_name='深圳卡号'),
        ),
        migrations.AlterField(
            model_name='information',
            name='contact_email',
            field=models.CharField(max_length=60, null=True, verbose_name='联系邮箱'),
        ),
        migrations.AlterField(
            model_name='information',
            name='contact_mob',
            field=models.CharField(max_length=60, null=True, verbose_name='联系手机'),
        ),
        migrations.AlterField(
            model_name='information',
            name='contact_tel',
            field=models.CharField(max_length=60, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='information',
            name='contact_weixin',
            field=models.CharField(max_length=60, null=True, verbose_name='联系微信'),
        ),
        migrations.AlterField(
            model_name='information',
            name='contacts',
            field=models.CharField(max_length=60, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='information',
            name='end_date',
            field=models.DateField(null=True, verbose_name='账户销户日期'),
        ),
        migrations.AlterField(
            model_name='information',
            name='notes',
            field=models.CharField(max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='information',
            name='salesman',
            field=models.CharField(max_length=60, null=True, verbose_name='认领销售员'),
        ),
        migrations.AlterField(
            model_name='information',
            name='start_date',
            field=models.DateField(null=True, verbose_name='账户启用日期'),
        ),
        migrations.AlterField(
            model_name='information',
            name='status',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='trader',
            field=models.CharField(max_length=60, null=True, verbose_name='认领交易员'),
        ),
        migrations.AlterField(
            model_name='information',
            name='type',
            field=models.CharField(max_length=60, null=True, verbose_name='账户类型'),
        ),
    ]
