# Generated by Django 3.2.8 on 2021-10-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('file_name', models.CharField(max_length=100, verbose_name='文件名')),
                ('status', models.IntegerField(verbose_name='有效标志')),
            ],
        ),
    ]
