# Generated by Django 3.2.8 on 2021-10-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=20)),
                ('loginname', models.CharField(max_length=30)),
                ('password', models.IntegerField(max_length=20)),
                ('app_id', models.CharField(max_length=30)),
                ('app_secret', models.CharField(max_length=30)),
                ('access_token', models.CharField(max_length=30)),
            ],
        ),
    ]
