# Generated by Django 3.2.8 on 2021-10-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('loginname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('app_id', models.CharField(max_length=30)),
                ('app_secret', models.CharField(max_length=30)),
                ('access_token', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Persion',
        ),
    ]
