# Generated by Django 3.2.8 on 2021-10-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20211013_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Login_WX',
        ),
    ]
