# Generated by Django 3.2.8 on 2021-10-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_person_login_wx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login_WX',
            new_name='WX_Login',
        ),
    ]
